apiVersion: v1
kind: Namespace
metadata:
  name: compose-sample
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: compose-sample
  namespace: compose-sample
spec:
  interval: 1m
  url: https://code.vt.edu/mikesir/local-cluster.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: compose-sample
  namespace: compose-sample
spec:
  interval: 1m
  path: "./"
  prune: true
  targetNamespace: compose-sample
  sourceRef:
    kind: GitRepository
    name: compose-sample
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: compose-sample-v2
  namespace: compose-sample
spec:
  interval: 2m
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: compose-helm-chart
        namespace: default
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: compose-values
      valuesKey: app.compose