name: Manifest Generation

on:
  push:
    branches:
      - main
    paths: 
      - 'docker-compose.yml'
  workflow_dispatch:
jobs:
  generate-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        
      - name: Add helm repo
        run: |
          helm repo add mikesir87 https://charts.mikesir87.io
          helm repo update
      - name: Generate k8s manifests
        run: |
          helm template -f docker-compose.yml mikesir87/compose-deployer > manifests/app.yaml
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "Generated new manifests"
